# .gitlab-ci.yml for mkdocs-material
#
# == Reference:
#   - https://docs.gitlab.com/ee/ci/yaml/
#   - https://docs.gitlab.com/ee/ci/multi_project_pipelines.html
#
stages:
  - build
  - readme

variables:
  CI_REGISTRY_IMAGE: index.docker.io/joshbeard/mkdocs-material
  CI_REGISTRY: docker.io
  CI_REGISTRY_USER: joshbeard

# ------------------------------------------------------------------------------
# == Docker Build
# ------------------------------------------------------------------------------
#
.docker_build:
  image: docker:20
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASS} ${CI_REGISTRY}
  script:
    - docker build --pull
      -t ${CI_REGISTRY_IMAGE}:${IMAGE_TAG}
      --build-arg requirements=${REQUIREMENTS_FILE}
      -f ${DOCKERFILE} .
    - docker push ${CI_REGISTRY_IMAGE}:${IMAGE_TAG}
  only:
    refs:
      - master

build:
  extends: .docker_build
  variables:
    IMAGE_TAG: '8'
    REQUIREMENTS_FILE: builds/8-requirements.txt
    DOCKERFILE: Dockerfile

build_alpine:
  extends: .docker_build
  variables:
    IMAGE_TAG: '8-alpine'
    REQUIREMENTS_FILE: builds/8-requirements.txt
    DOCKERFILE: Dockerfile-alpine

build_latest:
  extends: .docker_build
  variables:
    IMAGE_TAG: 'latest'
    REQUIREMENTS_FILE: builds/latest-requirements.txt
    DOCKERFILE: Dockerfile

build_latest_alpine:
  extends: .docker_build
  variables:
    IMAGE_TAG: 'latest-alpine'
    REQUIREMENTS_FILE: builds/latest-requirements.txt
    DOCKERFILE: Dockerfile-alpine

push_readme:
  image:
    name: peterevans/dockerhub-description:2
    entrypoint: ['']
  stage: readme
  variables:
    DOCKERHUB_USERNAME: $CI_REGISTRY_USER
    DOCKERHUB_REPOSITORY: ${CI_REGISTRY_USER}/mkdocs-material
    README_FILEPATH: ${CI_PROJECT_DIR}/README.md
  script:
    - cd / && /entrypoint.sh
    - cat action.log
