ARG source_image=python:3.13.0a6-slim
FROM ${source_image}

ARG requirements=builds/9-requirements.txt

# Git is used for the git-revision plugin
RUN apt-get update \
  && apt-get install -y git \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

ARG USER_UID=1066
ARG USER_GID=1066
RUN groupadd -g $USER_GID mkdocs \
  && useradd -l -m \
  -u $USER_UID \
  -g $USER_GID \
  --home-dir /home/mkdocs \
  --shell /bin/bash \
  mkdocs

COPY ${requirements} /docs/requirements.txt

WORKDIR /docs

RUN pip install -r requirements.txt

USER mkdocs

# Expose MkDocs development server port
EXPOSE 8000

# Start development server by default
ENTRYPOINT ["mkdocs"]
CMD ["serve", "--dev-addr=0.0.0.0:8000"]
