ARG source_image=python:3.11-slim
FROM ${source_image}

ARG requirements=builds/8-requirements.txt

# Git is used for the git-revision plugin
RUN apt-get update \
  && apt-get install -y git \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

COPY ${requirements} /docs/requirements.txt

WORKDIR /docs

RUN pip install -r requirements.txt

# Expose MkDocs development server port
EXPOSE 8000

# Start development server by default
ENTRYPOINT ["mkdocs"]
CMD ["serve", "--dev-addr=0.0.0.0:8000"]
