---
name: docker_build

on:
  push:
    branches:
      - 'master'
  schedule:
    - cron: "0 5 * * 1"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          -
            tags: 'joshbeard/mkdocs-material:9,joshbeard/mkdocs-material:9-alpine'
            build-args: requirements=builds/9-requirements.txt
            file: Dockerfile
          -
            tags: 'joshbeard/mkdocs-material:latest,joshbeard/mkdocs-material:latest-alpine'
            build-args: requirements=builds/latest-requirements.txt
            file: Dockerfile
          -
            tags: 'joshbeard/mkdocs-material:9-slim'
            build-args: requirements=builds/9-requirements.txt
            file: Dockerfile-slim
          -
            tags: 'joshbeard/mkdocs-material:latest-slim'
            build-args: requirements=builds/latest-requirements.txt
            file: Dockerfile-slim

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build latest
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ matrix.tags }}
          build-args: ${{ matrix.build-args }}
          file: ${{ matrix.file }}
  doc:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@master
      - uses: meeDamian/sync-readme@v1.0.6
        with:
          user: ${{ secrets.DOCKERHUB_USERNAME }}
          pass: ${{ secrets.DOCKERHUB_TOKEN }}
          slug: joshbeard/mkdocs-material
          readme: ./README.md
          description: MkDocs with the MkDocs-Material theme and plugins
